[[events]]
name = "Toggle Screen"
key_state = "pressed"
keys = ["KEY_POWER"]
command = "/usr/local/bin/toggle-screen.sh"

[[events]]
name = "Panic Reboot"
key_state = "pressed"
keys = ["KEY_VOLUMEDOWN", "KEY_POWER"]
command = "/sbin/reboot"