default_border none
assign [title="HID-UI"] workspace 1
assign [title="HIDLock"] workspace 10
exec swaymsg workspace 10
for_window [title="HID-UI"] fullscreen enable
for_window [title="HIDLock"] fullscreen enable

# Disable hardware-accelerated cursor logic
seat seat0 xcursor_theme default 24

output * modeline 173.00 1080 1144 1256 1440 1920 1928 1932 2000 -hsync +vsync
output * mode 1080x1920
output * bg #000000 solid_color

bindsym XF86PowerOff exec ~/bacon-experiments/HID/toggle-screen.sh
bindsym XF86AudioRaiseVolume exec swaymsg workspace 10

# exec lisgd -d /dev/input/event3 \
#  -g "1,U,*,*,~/bacon-experiments/iBacon/swipe.sh" \
#  -g "2,D,*,*,~/bacon-experiments/iBacon/keyboard.sh" \
#  -g "1,D,*,*,~/bacon-experiments/iBacon/cc.sh"

# exec waybar -c ~/bacon-experiments/iBacon/waybar.json -s ~/bacon-experiments/iBacon/waybar.css
exec sleep 1 && ~/bacon-experiments/HID/HID-app
# exec wvkbd-mobintl --hidden